issuer: https://token.actions.githubusercontent.com
subject: repo:celonis/jt-test-octo-sts-foo:ref:refs/heads/main
claim_pattern:
  workflow_ref: celonis/jt-test-octo-sts-foo/.github/workflows/use-action.yaml@refs/heads/main

repositories:
- cfg-ibc
- jt-test-octo-sts-bar

permissions:
  contents: read